spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: leo77777

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: warn
    com.blog: info
  file:
    name: log/blog-pro.log

server:
  port: 8081